# Equivalence relations
## Evaluating a psychological phenomena on machine learning algorithms *

* WORK IN PROGRESS

This python script contains arrays on the task of evaluating relational derived response as a psychological phenomena related with complex behaviors such as cognition or language from a behaviorist viewpoint.

The data are arrays of two list of bits where the first one is the encoded (sample) set of stimulus presented. The second is the (target) expected correct answer. 

# References

Sidman, M. (2000). Equivalence relations and the reinforcement contingency. Journal of the Experimental Analysis of Behavior, 74(1), 127–146. http://doi.org/10.1901/jeab.2000.74-127
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1284788/

Sidman, M. (2009). Equivalence Relations and Behavior: An Introductory Tutorial. The Analysis of Verbal Behavior, 25(1), 5–17.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2779070/

http://www.txaba.org/files/pdfs/Conference2017/StimulusEquivalence_Vaidya.pdf

## also check:

Testing Response-Stimulus Equivalence Relations Using Differential Responses as a Sample
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1592360/

In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

#pybrain net
import pybrain
from pybrain.datasets import UnsupervisedDataSet, SupervisedDataSet
from pybrain.tools.shortcuts import buildNetwork
from pybrain.supervised.trainers import BackpropTrainer
from pybrain.tools.validation import Validator

#scikit-learn
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

#datasets
import train_datasets as tr_dat

In [ ]:
train_symmetry_a_b=[[[1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0],[1,0,0]],
                    [[1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1],[1,0,0]],#
                    [[1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0],[1,0,0]],
                    [[1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1],[1,0,0]],
                    [[1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0],[1,0,0]],
                    [[1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0],[1,0,0]],
                    [[1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0],[0,1,0]],
                    [[1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1],[0,1,0]],
                    [[1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0],[0,1,0]],#
                    [[1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1],[0,1,0]],
                    [[1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0],[0,1,0]],
                    [[1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0],[0,1,0]],
                    [[1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0],[0,0,1]],#
                    [[1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0],[0,0,1]],
                    [[1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0],[0,0,1]],
                    [[1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0],[0,0,1]],
                    [[1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0],[0,0,1]],
                    [[1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0],[0,0,1]],
                    [[1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1],[0,0,0]], #A-CDE O_N
                    [[1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0],[0,0,0]], #A-CED O_N
                    [[1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1],[0,0,0]], #A-DCE O_N
                    [[1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0],[0,0,0]], #A-DEC O_N
                    [[1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0],[0,0,0]], #A-ECD O_N
                    [[1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0],[0,0,0]] #A-EDC O_N
                   ]
#a_b

In [ ]:
Dtrain = SupervisedDataSet(20,3) # define a dataset in pybrain
[Dtrain.addSample(smpl[0],smpl[1]) for smpl in train_symmetry_a_b]
print(Dtrain)

In [ ]:
validator =  Validator()
net = buildNetwork(20,4,3, hiddenclass=pybrain.SigmoidLayer, outclass=pybrain.SigmoidLayer)
T = BackpropTrainer(net, learningrate=0.01, momentum=0.99)

In [ ]:
scores = []
for i in xrange(1500):
    T.trainOnDataset(Dtrain, 1)
    prediction = net.activateOnDataset(Dtrain)
    scores.append(validator.MSE(prediction, Dtrain.getField('target')))
plt.ylabel('Mean Square Error')
plt.xlabel('Iteration')
plt.plot(scores)

In [ ]:
#T.trainOnDataset(Dtrain, 1000)
#print net.params

In [ ]:
#[[1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1],[1,0,0]], #A-BCE #No entrenado
#[[1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0],[0,1,0]], #A-DBC #No entrenado
#[[1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0],[0,0,1]], #A-CDB #No entrenado
#[1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1]# A-CDE #No entrenado
#[1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1]# A-DCE #No entrenado
#[0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0]#B-CAD #Test de simetría #No entrenado
in_vals=[0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0]

net.activate(in_vals)

In [ ]:
[[net.activate(in_val[0]),in_val[1]] for in_val in train_symmetry_a_b]

In [ ]:
test_simetr_AB=[[[0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0],[1,0,0]],
                [[0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1],[1,0,0]],
                [[0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0],[1,0,0]],
                [[0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1],[1,0,0]],
                [[0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0],[1,0,0]],
                [[0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0],[1,0,0]],
                [[0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0],[0,1,0]],
                [[0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1],[0,1,0]],
                [[0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0],[0,1,0]],
                [[0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1],[0,1,0]],
                [[0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0],[0,1,0]],
                [[0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0],[0,1,0]],
                [[0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0],[0,0,1]],
                [[0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0],[0,0,1]],
                [[0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0],[0,0,1]],
                [[0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0],[0,0,1]],
                [[0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0],[0,0,1]],
                [[0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0],[0,0,1]]
               ]

In [ ]:
test_no_entren=[[[1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1],[1,0,0]], #A-BCE #No entrenado
                [[1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0],[0,1,0]], #A-DBC #No entrenado
                [[1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0],[0,0,1]], #A-CDB #No entrenado
                #[[1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1],[0,0,0]], #A-CDE O_N
                #[[1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0],[0,0,0]], #A-CED O_N
                #[[1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1],[0,0,0]], #A-DCE O_N
                [[1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0],[0,0,0]], #A-DEC O_N
                [[1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0],[0,0,0]] #A-ECD O_N
                #[[1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0],[0,0,0]], #A-EDC O_N
               ]

In [ ]:
[[net.activate(in_val[0]),in_val[1]] for in_val in test_simetr_AB]

In [ ]:
def mlp_simmetry(train_symmetry_a_b,in_vec=20,out_vec=3, train_length=1500):
    # train_symmetry_a_b = array de entrenamiento: valores entrada, valores de salida de la red
    # test_simetr_AB = array de test: valores entrada, valores de salida de la red
    # in_vec = longitud vector valores de entrada
    # out_vec = longitud vector valores de salida
    # train_length = Cantidad de ensayos de entrenamiento
    Dtrain = SupervisedDataSet(in_vec,out_vec) # define a dataset in pybrain
    [Dtrain.addSample(smpl[0],smpl[1]) for smpl in train_symmetry_a_b]
    validator =  Validator()
    net = buildNetwork(20,4,3, hiddenclass=pybrain.SigmoidLayer, outclass=pybrain.SigmoidLayer)
    T = BackpropTrainer(net, learningrate=0.01, momentum=0.99)
    scores = []
    for i in xrange(train_length):
        T.trainOnDataset(Dtrain, 1)
        prediction = net.activateOnDataset(Dtrain)
        scores.append(validator.MSE(prediction, Dtrain.getField('target')))
    plt.ylabel('Mean Square Error')
    plt.xlabel('Iteration')
    plt.plot(scores)
    print("**** Respuestas de entrenamiento")
    print(pd.DataFrame([[net.activate(in_val[0]),in_val[1]] for in_val in train_symmetry_a_b]))
    print ("Error ensayo final", scores[500-1])
    return net
    

In [ ]:
a_b_net=mlp_simmetry(train_symmetry_a_b,train_length=500)

In [ ]:
[[a_b_net.activate(in_val[0]),in_val[1]] for in_val in test_no_entren]

# Clasificadores de una capa


In [ ]:
import numpy as np

In [ ]:
stims={"A1":[1,0,0,0,0,0,0,0,0,0,0,0],
       "A2":[0,1,0,0,0,0,0,0,0,0,0,0],
       "A3":[0,0,1,0,0,0,0,0,0,0,0,0],
       "A4":[0,0,0,1,0,0,0,0,0,0,0,0],
       "B1":[0,0,0,0,1,0,0,0,0,0,0,0],
       "B2":[0,0,0,0,0,1,0,0,0,0,0,0],
       "B3":[0,0,0,0,0,0,1,0,0,0,0,0],
       "B4":[0,0,0,0,0,0,0,1,0,0,0,0],
       "C1":[0,0,0,0,0,0,0,0,1,0,0,0],
       "C2":[0,0,0,0,0,0,0,0,0,1,0,0],
       "C3":[0,0,0,0,0,0,0,0,0,0,1,0],
       "C4":[0,0,0,0,0,0,0,0,0,0,0,1]
      }

In [ ]:
test_1={"labels":[[i,j,k,l] for i in stims.keys() for j in stims.keys()for k in stims.keys()for l in stims.keys()],
        "values_x":[np.array(i+j+k+l) for i in stims.values() for j in stims.values()for k in stims.values()for l in stims.values()],
        "values_y":[np.bitwise_or(np.bitwise_or(np.bitwise_or(i,j),k),l) for i in stims.values() for j in stims.values()for k in stims.values()for l in stims.values()]
        }

In [ ]:
len(test_1["values_y"])

In [ ]:
import random
random.randrange(len(test_1["values_y"]))

In [ ]:
n_dat=random.randrange(len(test_1["values_y"]))
print(n_dat)
print(test_1["labels"][n_dat])
print(test_1["values_x"][n_dat])
print(test_1["values_y"][n_dat])

In [ ]:
labels=[[i,j,k,l] for i in stims.keys() for j in stims.keys()for k in stims.keys()for l in stims.keys()]
values_x=[np.array(i+j+k+l) for i in stims.values() for j in stims.values()for k in stims.values()for l in stims.values()]
test1_y=[list(np.bitwise_or(np.bitwise_or(np.bitwise_or(i,j),k),l)) for i in stims.values() for j in stims.values()for k in stims.values()for l in stims.values()]


In [ ]:
[[labels[i], values_x[i]]for i in xrange(len(labels))]

In [ ]:
from sklearn.neural_network import MLPClassifier
X = [[0., 0.], [1., 1.]]
y = [0, 1]
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)

clf.fit(X,y)

In [ ]:
clf.fit(values_x,test1_y)

class sklearn.neural_network.MLPClassifier(hidden_layer_sizes=(100, ), activation=’relu’, solver=’adam’, alpha=0.0001, batch_size=’auto’, learning_rate=’constant’, learning_rate_init=0.001, power_t=0.5, max_iter=200, shuffle=True, random_state=None, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True, early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08)[source]


In [ ]:
def test_1_view ():
    n_dat=random.randrange(len(values_x))
    print(n_dat)
    print(values_x[n_dat,0:12])
    print(values_x[n_dat,12:24])
    print(values_x[n_dat,24:36])
    print(values_x[n_dat,36:48])
    print(test1_y[n_dat,:])
    print(labels[n_dat,:])

In [ ]:
test_1_view()

In [ ]:
n_dat=random.randrange(len(test_1["values_y"]))
print(n_dat)
print(test_1["labels"][n_dat])
print(test_1["values_x"][n_dat])
print(test_1["values_y"][n_dat])
clf.predict(np.array(test_1["values_x"][n_dat]).reshape(1, -1))

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_moons, make_circles, make_classification
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis


In [ ]:
h = .02  # step size in the mesh

names = ["Nearest Neighbors", "Linear SVM", "RBF SVM", "Gaussian Process",
         "Decision Tree", "Random Forest", "Neural Net", "AdaBoost",
         "Naive Bayes", "QDA"]

classifiers = [
    KNeighborsClassifier(3),
    SVC(kernel="linear", C=0.025),
    SVC(gamma=2, C=1),
    GaussianProcessClassifier(1.0 * RBF(1.0), warm_start=True),
    DecisionTreeClassifier(max_depth=5),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
    MLPClassifier(alpha=1),
    AdaBoostClassifier(),
    GaussianNB(),
    QuadraticDiscriminantAnalysis()]

X, y = make_classification(n_features=2, n_redundant=0, n_informative=2,
                           random_state=1, n_clusters_per_class=1)
rng = np.random.RandomState(2)
X += 2 * rng.uniform(size=X.shape)
linearly_separable = (X, y)

datasets = [make_moons(noise=0.3, random_state=0),
            make_circles(noise=0.2, factor=0.5, random_state=1),
            linearly_separable
            ]

In [ ]:
figure = plt.figure(figsize=(27, 9))
i = 1
# iterate over datasets
for ds_cnt, ds in enumerate(datasets):
    # preprocess dataset, split into training and test part
    X, y = ds
    X = StandardScaler().fit_transform(X)
    X_train, X_test, y_train, y_test = \
        train_test_split(X, y, test_size=.4, random_state=42)

    x_min, x_max = X[:, 0].min() - .5, X[:, 0].max() + .5
    y_min, y_max = X[:, 1].min() - .5, X[:, 1].max() + .5
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                         np.arange(y_min, y_max, h))

    # just plot the dataset first
    cm = plt.cm.RdBu
    cm_bright = ListedColormap(['#FF0000', '#0000FF'])
    ax = plt.subplot(len(datasets), len(classifiers) + 1, i)
    if ds_cnt == 0:
        ax.set_title("Input data")
    # Plot the training points
    ax.scatter(X_train[:, 0], X_train[:, 1], c=y_train, cmap=cm_bright,
               edgecolors='k')
    # and testing points
    ax.scatter(X_test[:, 0], X_test[:, 1], c=y_test, cmap=cm_bright, alpha=0.6,
               edgecolors='k')
    ax.set_xlim(xx.min(), xx.max())
    ax.set_ylim(yy.min(), yy.max())
    ax.set_xticks(())
    ax.set_yticks(())
    i += 1

    # iterate over classifiers
    for name, clf in zip(names, classifiers):
        ax = plt.subplot(len(datasets), len(classifiers) + 1, i)
        clf.fit(X_train, y_train)
        score = clf.score(X_test, y_test)

        # Plot the decision boundary. For that, we will assign a color to each
        # point in the mesh [x_min, x_max]x[y_min, y_max].
        if hasattr(clf, "decision_function"):
            Z = clf.decision_function(np.c_[xx.ravel(), yy.ravel()])
        else:
            Z = clf.predict_proba(np.c_[xx.ravel(), yy.ravel()])[:, 1]

        # Put the result into a color plot
        Z = Z.reshape(xx.shape)
        ax.contourf(xx, yy, Z, cmap=cm, alpha=.8)

        # Plot also the training points
        ax.scatter(X_train[:, 0], X_train[:, 1], c=y_train, cmap=cm_bright,
                   edgecolors='k')
        # and testing points
        ax.scatter(X_test[:, 0], X_test[:, 1], c=y_test, cmap=cm_bright,
                   edgecolors='k', alpha=0.6)

        ax.set_xlim(xx.min(), xx.max())
        ax.set_ylim(yy.min(), yy.max())
        ax.set_xticks(())
        ax.set_yticks(())
        if ds_cnt == 0:
            ax.set_title(name)
        ax.text(xx.max() - .3, yy.min() + .3, ('%.2f' % score).lstrip('0'),
                size=15, horizontalalignment='right')
        i += 1

plt.tight_layout()
plt.show()

In [ ]:
X_train

# Reflexivity test dataset_2

In [ ]:
import numpy as np
import random

In [ ]:
stims={"A1":[1,0,0,0,0,0,0,0,0,0,0,0],
       "A2":[0,1,0,0,0,0,0,0,0,0,0,0],
       "A3":[0,0,1,0,0,0,0,0,0,0,0,0],
       "A4":[0,0,0,1,0,0,0,0,0,0,0,0],
       "B1":[0,0,0,0,1,0,0,0,0,0,0,0],
       "B2":[0,0,0,0,0,1,0,0,0,0,0,0],
       "B3":[0,0,0,0,0,0,1,0,0,0,0,0],
       "B4":[0,0,0,0,0,0,0,1,0,0,0,0],
       "C1":[0,0,0,0,0,0,0,0,1,0,0,0],
       "C2":[0,0,0,0,0,0,0,0,0,1,0,0],
       "C3":[0,0,0,0,0,0,0,0,0,0,1,0],
       "C4":[0,0,0,0,0,0,0,0,0,0,0,1]
      }

options={"O_1":[1,0,0],
         "O_2":[0,1,0],
         "O_3":[0,0,1],
         "O_0":[0,0,0],
        }

labels=np.array([[i,j,k,l] for i in stims.keys() for j in stims.keys()for k in stims.keys()for l in stims.keys()])
values_x=np.array([np.array(i+j+k+l) for i in stims.values() for j in stims.values()for k in stims.values()for l in stims.values()])

symmetry_A1_labels=labels[(labels[:,0]=="A1")&((labels[:,1]=="A1")|(labels[:,2]=="A1")|(labels[:,3]=="A1"))]
symmetry_A1_values=values_x[(labels[:,0]=="A1")&((labels[:,1]=="A1")|(labels[:,2]=="A1")|(labels[:,3]=="A1"))]

symmetry_A1_values=symmetry_A1_values[np.sum((symmetry_A1_labels[:,1:]=="A1")*1.0, axis=1)==1]
symmetry_A1_labels=symmetry_A1_labels[np.sum((symmetry_A1_labels[:,1:]=="A1")*1.0, axis=1)==1]
symmetry_A1_y=(symmetry_A1_labels[:,1:]=="A1")*1

print(symmetry_A1_labels.shape)
print(symmetry_A1_values.shape)

In [ ]:
n_dat=random.randrange(len(symmetry_A1_values))
print(n_dat)
print(symmetry_A1_values[n_dat,0:12])
print(symmetry_A1_values[n_dat,12:24])
print(symmetry_A1_values[n_dat,24:36])
print(symmetry_A1_values[n_dat,36:48])
print(symmetry_A1_y[n_dat,:])
print(symmetry_A1_labels[n_dat,:])

In [ ]:
symm_labels=[]
symm_values=[]
symm_y=[]
for lab in stims.keys(): 
    symmetry_labels=labels[(labels[:,0]==lab)&((labels[:,1]==lab)|(labels[:,2]==lab)|(labels[:,3]==lab))]
    symmetry_values=values_x[(labels[:,0]==lab)&((labels[:,1]==lab)|(labels[:,2]==lab)|(labels[:,3]==lab))]

    symmetry_values=symmetry_values[np.sum((symmetry_labels[:,1:]==lab)*1.0, axis=1)==1]
    symmetry_labels=symmetry_labels[np.sum((symmetry_labels[:,1:]==lab)*1.0, axis=1)==1]
    symmetry_y=(symmetry_labels[:,1:]==lab)*1
    
    [symm_labels.append(lbl) for lbl in symmetry_labels]
    [symm_values.append(vle) for vle in symmetry_values]
    [symm_y.append(vly) for vly in symmetry_y]
symm_labels=np.array(symm_labels)
symm_values=np.array(symm_values)
symm_y=np.array(symm_y)

In [ ]:
print (symm_labels.shape,
       symm_values.shape,
       symm_y.shape)

In [ ]:
n_dat=random.randrange(len(symm_values))
print(n_dat)
print(symm_values[n_dat,0:12])
print(symm_values[n_dat,12:24])
print(symm_values[n_dat,24:36])
print(symm_values[n_dat,36:48])
print(symm_y[n_dat,:])
print(symm_labels[n_dat,:])

In [ ]:
A=np.array([[11,12,13,14],[25,26,27,28],[39,30,31,32]])
print(A)
B=A+30
print(B)
C=[]
[C.append(Ai) for Ai in B]
[C.append(Bi) for Bi in B]
np.array(C)

In [ ]:
np.array([])


In [ ]:
#symmetry_A1_labels
labels[(labels[:,0]=="A1")&((labels[:,1]=="A1")|(labels[:,2]=="A1")|(labels[:,3]=="A1"))]

In [ ]:
(np.sum((symmetry_A1_labels[:,1:]=="A1")*1.0, axis=1)==1)*1

In [ ]:
symmetry_A1_y.shape

# Symmetry

In [1]:
import random
import numpy as np

stims={"A1":[1,0,0,0,0,0,0,0,0,0,0,0],
       "A2":[0,1,0,0,0,0,0,0,0,0,0,0],
       "A3":[0,0,1,0,0,0,0,0,0,0,0,0],
       "A4":[0,0,0,1,0,0,0,0,0,0,0,0],
       "B1":[0,0,0,0,1,0,0,0,0,0,0,0],
       "B2":[0,0,0,0,0,1,0,0,0,0,0,0],
       "B3":[0,0,0,0,0,0,1,0,0,0,0,0],
       "B4":[0,0,0,0,0,0,0,1,0,0,0,0],
       "C1":[0,0,0,0,0,0,0,0,1,0,0,0],
       "C2":[0,0,0,0,0,0,0,0,0,1,0,0],
       "C3":[0,0,0,0,0,0,0,0,0,0,1,0],
       "C4":[0,0,0,0,0,0,0,0,0,0,0,1]
      }

options={"O_1":[1,0,0],
         "O_2":[0,1,0],
         "O_3":[0,0,1],
         "O_0":[0,0,0],
        }

labels=np.array([[i,j,k,l] for i in stims.keys() for j in stims.keys()for k in stims.keys()for l in stims.keys()])
values_x=np.array([np.array(i+j+k+l) for i in stims.values() for j in stims.values()for k in stims.values()for l in stims.values()])

- The sample:
    - must be the first element of the train pair.
    - it has to be excluded on the comparator. 
    - ** does all the comparators must be the same mode as the target stimulus?**
        - (Y) for experimental control
        - (Y) avoid validation combinations in the train dataset
        
        
- The target stimulus must be only once in the comparisons set


In [2]:
train_pairs=np.array([["A1","B1"],["B1","C1"],
                      ["A2","B2"],["B2","C2"],
                      ["A3","B3"],["B3","C3"],
                      ["A4","B4"],["B4","C4"]])

## A-B B-C train

In [3]:
filt_train_x=np.any(
    [
        [((lbl[0]==pair[0])& #The sample is the first element of the pair
          (lbl[1][0]==pair[1][0])& #The comparator 1 has the same mode (letter) of the second element of the pair
          (lbl[2][0]==pair[1][0])& #The comparator 2 has the same mode (letter) of the second element of the pair
          (lbl[3][0]==pair[1][0])& #The comparator 3 has the same mode (letter) of the second element of the pair
          ((lbl[1]==pair[1])|(lbl[2]==pair[1])|(lbl[3]==pair[1]))&# any of the comparators is the second element of the pair
          ((lbl[1]==pair[1])+(lbl[2]==pair[1])+(lbl[3]==pair[1])==1)# the second element of the pair is presented once in the comparators
         ) for pair in train_pairs] for lbl in labels],# for any of the pairs on every label
axis=1)

train_values=values_x[filt_train_x]
train_labels=  labels[filt_train_x]

train_response=np.any(np.array([
    [[
        ((lbl[0]==pair[0])&(lbl[1]==pair[1])), #The sample is the first element of the pair and the first  comparator is the second element of the pair
        ((lbl[0]==pair[0])&(lbl[2]==pair[1])), #The sample is the first element of the pair and the second comparator is the second element of the pair
        ((lbl[0]==pair[0])&(lbl[3]==pair[1])) #The sample is the first element of the pair and the third  comparator is the second element of the pair
    ] for pair in train_pairs] for lbl in train_labels]# for any of the pairs on every label
), axis=1)*1

In [4]:
def view_train():
    n_dat=random.randrange(len(train_labels))
    print(n_dat)
    print(train_values[n_dat,0:12])
    print(train_values[n_dat,12:24])
    print(train_values[n_dat,24:36])
    print(train_values[n_dat,36:48])
    print(train_response[n_dat,:])
    print(train_labels[n_dat,:])

In [5]:
n_stim=random.randrange(len(train_labels))
n_stim

5

In [6]:
view_train()

105
[0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0]
[0 1 0]
['A2' 'B1' 'B2' 'B1']


In [7]:
pair=symm_train_pairs[0]
n_lbl=random.randrange(len(labels))
sample=0
compar_1=1
compar_2=2
compar_3=3
compar_mode_letter=pair[1][0]

NameError: name 'symm_train_pairs' is not defined

In [8]:
np.array([[(pair+lbl) for pair in ["P1","P2","P3"]] for lbl in ["l1","l2","l3","l4"]])
#print(symm_train_pairs)
#print()

array([['P1l1', 'P2l1', 'P3l1'],
       ['P1l2', 'P2l2', 'P3l2'],
       ['P1l3', 'P2l3', 'P3l3'],
       ['P1l4', 'P2l4', 'P3l4']], 
      dtype='|S4')

In [ ]:
labels[filt_1]

In [ ]:
np.sum(filt_1)

In [ ]:
True+False+False==1

In [ ]:
symm_labels=[]
symm_values=[]
symm_y=[]
for lab in stims.keys(): 
    symmetry_labels=labels[(labels[:,0]==lab)&((labels[:,1]==lab)|(labels[:,2]==lab)|(labels[:,3]==lab))]
    symmetry_values=values_x[(labels[:,0]==lab)&((labels[:,1]==lab)|(labels[:,2]==lab)|(labels[:,3]==lab))]

    symmetry_values=symmetry_values[np.sum((symmetry_labels[:,1:]==lab)*1.0, axis=1)==1]
    symmetry_labels=symmetry_labels[np.sum((symmetry_labels[:,1:]==lab)*1.0, axis=1)==1]
    symmetry_y=(symmetry_labels[:,1:]==lab)*1
    
    [symm_labels.append(lbl) for lbl in symmetry_labels]
    [symm_values.append(vle) for vle in symmetry_values]
    [symm_y.append(vly) for vly in symmetry_y]
symm_labels=np.array(symm_labels)
symm_values=np.array(symm_values)
symm_y=np.array(symm_y)

# Symmetry evaluation

In [13]:
filt_symm_x=np.any(
    [
        [((lbl[0]==pair[1])& #The sample is the second element of the pair
          (lbl[1][0]==pair[0][0])& #The comparator 1 has the same mode (letter) of the first element of the pair
          (lbl[2][0]==pair[0][0])& #The comparator 2 has the same mode (letter) of the first element of the pair
          (lbl[3][0]==pair[0][0])& #The comparator 3 has the same mode (letter) of the first element of the pair
          ((lbl[1]==pair[0])|(lbl[2]==pair[0])|(lbl[3]==pair[0]))&# any of the comparators is the first element of the pair
          ((lbl[1]==pair[0])+(lbl[2]==pair[0])+(lbl[3]==pair[0])==1)# the first element of the pair is presented once in the comparators
         ) for pair in train_pairs] for lbl in labels],# for any of the pairs on every label
axis=1)

symmetry_values=values_x[filt_symm_x]
symmetry_labels=  labels[filt_symm_x]

symmetry_response=np.any(np.array([
    [[
        ((lbl[0]==pair[1])&(lbl[1]==pair[0])), #The sample is the second element of the pair and the first  comparator is the first element of the pair
        ((lbl[0]==pair[1])&(lbl[2]==pair[0])), #The sample is the second element of the pair and the second comparator is the first element of the pair
        ((lbl[0]==pair[1])&(lbl[3]==pair[0]))  #The sample is the second element of the pair and the third  comparator is the first element of the pair
    ] for pair in train_pairs] for lbl in symmetry_labels]# for any of the pairs on every label
), axis=1)*1

In [14]:
def view_symmetry():
    n_dat=random.randrange(len(symmetry_labels))
    print(n_dat)
    print(symmetry_values[n_dat,0:12])
    print(symmetry_values[n_dat,12:24])
    print(symmetry_values[n_dat,24:36])
    print(symmetry_values[n_dat,36:48])
    print(symmetry_response[n_dat,:])
    print(symmetry_labels[n_dat,:])

In [15]:
view_symmetry()

44
[0 0 0 0 0 1 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0]
[1 0 0]
['B2' 'A2' 'A3' 'A4']


# Transitivity and equivalence Evaluation

In [17]:
eval_pairs=np.array([["A1","C1"],
                      ["A2","C2"],
                      ["A3","C3"],
                      ["A4","C4"]])

In [18]:
#Transitivity
filt_transitivity_x=np.any(
    [
        [((lbl[0]==pair[0])& #The sample is the first element of the pair
          (lbl[1][0]==pair[1][0])& #The comparator 1 has the same mode (letter) of the second element of the pair
          (lbl[2][0]==pair[1][0])& #The comparator 2 has the same mode (letter) of the second element of the pair
          (lbl[3][0]==pair[1][0])& #The comparator 3 has the same mode (letter) of the second element of the pair
          ((lbl[1]==pair[1])|(lbl[2]==pair[1])|(lbl[3]==pair[1]))&# any of the comparators is the second element of the pair
          ((lbl[1]==pair[1])+(lbl[2]==pair[1])+(lbl[3]==pair[1])==1)# the second element of the pair is presented once in the comparators
         ) for pair in eval_pairs] for lbl in labels],# for any of the pairs on every label
axis=1)

transitivity_values=values_x[filt_transitivity_x]
transitivity_labels=  labels[filt_transitivity_x]

transitivity_response=np.any(np.array([
    [[
        ((lbl[0]==pair[0])&(lbl[1]==pair[1])), #The sample is the first element of the pair and the first  comparator is the second element of the pair
        ((lbl[0]==pair[0])&(lbl[2]==pair[1])), #The sample is the first element of the pair and the second comparator is the second element of the pair
        ((lbl[0]==pair[0])&(lbl[3]==pair[1])) #The sample is the first element of the pair and the third  comparator is the second element of the pair
    ] for pair in eval_pairs] for lbl in transitivity_labels]# for any of the pairs on every label
), axis=1)*1

In [21]:
def view_transitivity():
    n_dat=random.randrange(len(transitivity_labels))
    print(n_dat)
    print(transitivity_values[n_dat,0:12])
    print(transitivity_values[n_dat,12:24])
    print(transitivity_values[n_dat,24:36])
    print(transitivity_values[n_dat,36:48])
    print(transitivity_response[n_dat,:])
    print(transitivity_labels[n_dat,:])

In [22]:
view_transitivity()

17
[1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1]
[1 0 0]
['A1' 'C1' 'C2' 'C4']


In [23]:
# Equivalence
filt_equivalence=np.any(
    [
        [((lbl[0]==pair[1])& #The sample is the second element of the pair
          (lbl[1][0]==pair[0][0])& #The comparator 1 has the same mode (letter) of the first element of the pair
          (lbl[2][0]==pair[0][0])& #The comparator 2 has the same mode (letter) of the first element of the pair
          (lbl[3][0]==pair[0][0])& #The comparator 3 has the same mode (letter) of the first element of the pair
          ((lbl[1]==pair[0])|(lbl[2]==pair[0])|(lbl[3]==pair[0]))&# any of the comparators is the first element of the pair
          ((lbl[1]==pair[0])+(lbl[2]==pair[0])+(lbl[3]==pair[0])==1)# the first element of the pair is presented once in the comparators
         ) for pair in eval_pairs] for lbl in labels],# for any of the pairs on every label
axis=1)

equivalence_values=values_x[filt_equivalence]
equivalence_labels=  labels[filt_equivalence]

equivalence_response=np.any(np.array([
    [[
        ((lbl[0]==pair[1])&(lbl[1]==pair[0])), #The sample is the second element of the pair and the first  comparator is the first element of the pair
        ((lbl[0]==pair[1])&(lbl[2]==pair[0])), #The sample is the second element of the pair and the second comparator is the first element of the pair
        ((lbl[0]==pair[1])&(lbl[3]==pair[0]))  #The sample is the second element of the pair and the third  comparator is the first element of the pair
    ] for pair in eval_pairs] for lbl in equivalence_labels]# for any of the pairs on every label
), axis=1)*1

In [24]:
def view_equivalence():
    n_dat=random.randrange(len(equivalence_labels))
    print(n_dat)
    print(equivalence_values[n_dat,0:12])
    print(equivalence_values[n_dat,12:24])
    print(equivalence_values[n_dat,24:36])
    print(equivalence_values[n_dat,36:48])
    print(equivalence_response[n_dat,:])
    print(equivalence_labels[n_dat,:])

In [25]:
view_equivalence()

71
[0 0 0 0 0 0 0 0 1 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0]
[0 1 0]
['C1' 'A2' 'A1' 'A4']
